kind: pipeline
name: GNU GCC TC ARM BUILD

clone:
  disable: true

steps:
- name: GNU GCC ARM
  image: ubuntu:latest
  environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      TG_BOT_API:
        from_secret: TG_BOT_API
      CHAT_ID:
        from_secret: CHAT_ID
      CHANNEL_ID:
        from_secret: CHANNEL_ID
  commands:
    - "export GITHUB_TOKEN"
    - apt-get update -y && apt-get upgrade -y && DEBIAN_FRONTEND=noninteractive apt-get install flex bison sudo git ncurses-dev texinfo gcc gperf patch libtool automake g++ libncurses5-dev gawk subversion expat libexpat1-dev python-all-dev binutils-dev libgcc1 bc libisl-dev libcap-dev autoconf autoconf-archive libgmp-dev build-essential gcc-multilib g++-multilib pkg-config libmpc-dev libmpfr-dev autopoint gettext liblzma-dev libssl-dev libz-dev -y
    - git clone https://github.com/fiqri19102002/build-tools-gcc.git builder && cd builder
    - script -c "bash -x build -a arm -s gnu -v 11 -V -p zstd -tm" /drone/src/build-arm-gnu-gcc.log

---
kind: pipeline
name: GNU GCC TC ARM64 BUILD

clone:
  disable: true

steps:
- name: GNU GCC ARM64
  image: ubuntu:latest
  environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      TG_BOT_API:
        from_secret: TG_BOT_API
      CHAT_ID:
        from_secret: CHAT_ID
      CHANNEL_ID:
        from_secret: CHANNEL_ID
  commands:
    - "export GITHUB_TOKEN"
    - apt-get update -y && apt-get upgrade -y && DEBIAN_FRONTEND=noninteractive apt-get install flex bison sudo git ncurses-dev texinfo gcc gperf patch libtool automake g++ libncurses5-dev gawk subversion expat libexpat1-dev python-all-dev binutils-dev libgcc1 bc libisl-dev libcap-dev autoconf autoconf-archive libgmp-dev build-essential gcc-multilib g++-multilib pkg-config libmpc-dev libmpfr-dev autopoint gettext liblzma-dev libssl-dev libz-dev -y
    - git clone https://github.com/fiqri19102002/build-tools-gcc.git builder && cd builder
    - script -c "bash -x build -a arm64 -s gnu -v 11 -V -p zstd -tm" /drone/src/build-arm64-gnu-gcc.log
