kind: pipeline
name: GNU GCC TC ARM BUILD

clone:
  disable: true

steps:
- name: GNU GCC ARM
  image: archlinux:base-20210131.0.14634
  environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      TG_BOT_API:
        from_secret: TG_BOT_API
      CHAT_ID:
        from_secret: CHAT_ID
      CHANNEL_ID:
        from_secret: CHANNEL_ID
  commands:
    - "export GITHUB_TOKEN"
    - pacman -Sy base-devel git glibc curl subversion autoconf-archive tar xz pixz lzip aria2 zip parallel zstd rsync python python3 --noconfirm
    - git clone https://github.com/theradcolor/build-tools-gcc.git builder && cd builder
    - script -c "bash -x build -a arm -s gnu -v 11 -V -p zstd -tm" /drone/src/build-arm-gnu-gcc.log

---
kind: pipeline
name: GNU GCC TC ARM64 BUILD

clone:
  disable: true

steps:
- name: GNU GCC ARM64
  image: archlinux:base-20210131.0.14634
  environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
      TG_BOT_API:
        from_secret: TG_BOT_API
      CHAT_ID:
        from_secret: CHAT_ID
      CHANNEL_ID:
        from_secret: CHANNEL_ID
  commands:
    - "export GITHUB_TOKEN"
    - pacman -Sy base-devel git glibc curl subversion autoconf-archive tar xz pixz lzip aria2 zip parallel zstd rsync python python3 --noconfirm
    - git clone https://github.com/theradcolor/build-tools-gcc.git builder && cd builder
    - script -c "bash -x build -a arm64 -s gnu -v 11 -V -p zstd -tm" /drone/src/build-arm64-gnu-gcc.log
